import {CHALLENGES,challengeProgress} from './challenges.js?v=0.8.0';
const KEY='blacksite.career.v1',STAT_KEYS=['matches','wins','losses','rounds','roundWins','kills','deaths','headshots','shots','hits','plants','defuses','time','cleanRounds','precisionRounds'],MAP_KEYS=['helix','bastion','ironwood','zero'],WEAPON_KEYS=['ak47','mp5','rifle','sv98','m82','pistol','c9','h45'];
const CLASS={ak47:'RIFLE',rifle:'RIFLE',mp5:'SMG',sv98:'SNIPER',m82:'SNIPER',pistol:'SIDEARM',c9:'SIDEARM',h45:'SIDEARM'},number=v=>Number.isFinite(v)?Math.min(1e9,Math.max(0,v)):0;
export const levelForXP=xp=>1+Math.floor(Math.sqrt(number(xp)/300));
export function levelProgress(xp){xp=number(xp);const level=levelForXP(xp),start=300*(level-1)**2,end=300*level**2;return {level,start,end,current:xp-start,required:end-start,percent:100*(xp-start)/(end-start)};}
export const accuracy=(hits,shots)=>shots?Math.min(100,Math.round(hits/shots*100)):0;
function blank(){return {schema:1,xp:0,stats:Object.fromEntries(STAT_KEYS.map(k=>[k,0])),mapStats:{},difficultyWins:{easy:0,normal:0,hard:0},weaponStats:{},classes:[],badges:[],emblem:'deployment',processed:[],bests:{kills:0,headshots:0,accuracy:0}};}
export function sanitizeCareer(input){const p=blank();if(!input||typeof input!=='object'||Array.isArray(input))return p;p.xp=number(input.xp);for(const k of STAT_KEYS)p.stats[k]=number(input.stats?.[k]);p.stats.hits=Math.min(p.stats.hits,p.stats.shots);p.stats.headshots=Math.min(p.stats.headshots,p.stats.kills);for(const map of MAP_KEYS)if(input.mapStats?.[map])p.mapStats[map]={matches:number(input.mapStats[map].matches),wins:number(input.mapStats[map].wins),time:number(input.mapStats[map].time)};for(const k of ['easy','normal','hard'])p.difficultyWins[k]=number(input.difficultyWins?.[k]);for(const w of WEAPON_KEYS)if(input.weaponStats?.[w])p.weaponStats[w]=Object.fromEntries(['kills','shots','hits','time'].map(k=>[k,number(input.weaponStats[w][k])]));p.classes=[...new Set(Object.keys(p.weaponStats).filter(k=>p.weaponStats[k].kills>0).map(k=>CLASS[k]))];p.badges=Array.isArray(input.badges)?[...new Set(input.badges.filter(id=>CHALLENGES.some(c=>c.id===id)))]:[];p.emblem=p.badges.includes(input.emblem)?input.emblem:'deployment';p.processed=Array.isArray(input.processed)?input.processed.filter(k=>typeof k==='string'&&k.length<100).slice(-200):[];for(const k of ['kills','headshots','accuracy'])p.bests[k]=number(input.bests?.[k]);return p;}
export class Career {
 constructor(storage){this.storage=storage;this.sessionOnly=false;try{const s=this.getStorage();this.sessionOnly=!s;this.data=sanitizeCareer(JSON.parse(s?.getItem(KEY)||'{}'));}catch{this.data=blank();this.sessionOnly=true;}}
 getStorage(){return this.storage===undefined?globalThis.localStorage:this.storage;}
 save(){try{const s=this.getStorage();if(!s)throw Error('Storage unavailable');s.setItem(KEY,JSON.stringify(this.data));this.sessionOnly=false;}catch{this.sessionOnly=true;}if(globalThis.window?.dispatchEvent&&globalThis.CustomEvent)window.dispatchEvent(new CustomEvent('blacksite:career'));}
 addStats(stats,map,weaponUsage={}){for(const k of ['kills','deaths','headshots','shots','hits','plants','defuses','time'])this.data.stats[k]+=number(stats[k]);const m=this.data.mapStats[map]??={matches:0,wins:0,time:0};m.time+=number(stats.time);for(const [weapon,usage] of Object.entries(weaponUsage))if(WEAPON_KEYS.includes(weapon)){const w=this.data.weaponStats[weapon]??={kills:0,shots:0,hits:0,time:0};for(const k of ['kills','shots','hits','time'])w[k]+=number(usage[k]);}this.data.classes=[...new Set(Object.keys(this.data.weaponStats).filter(k=>this.data.weaponStats[k].kills>0).map(k=>CLASS[k]))];}
 recordRound({id,map,difficulty,win,stats,weaponUsage,complete=false,alive=false,damage=1,report=null}){if(this.data.processed.includes(id))return {xp:0,unlocks:[],level:levelProgress(this.data.xp),bests:[],challengeProgress:[]};this.data.processed.push(id);this.data.processed=this.data.processed.slice(-200);const before=this.data.xp,previous=challengeProgress(this.data);this.addStats(stats,map,weaponUsage);this.data.stats.rounds++;if(win)this.data.stats.roundWins++;if(win&&alive&&damage===0)this.data.stats.cleanRounds++;if(win&&stats.shots>=10&&accuracy(stats.hits,stats.shots)>=40)this.data.stats.precisionRounds++;let earned=100+(win?75:0)+number(stats.kills)*25+number(stats.headshots)*10+number(stats.plants)*40+number(stats.defuses)*60;if(complete){this.data.stats.matches++;this.data.stats[win?'wins':'losses']++;const m=this.data.mapStats[map];m.matches++;if(win){m.wins++;this.data.difficultyWins[difficulty]=(this.data.difficultyWins[difficulty]||0)+1;}earned+=win?150:75;}const unlocks=[];for(const c of challengeProgress(this.data))if(c.complete&&!this.data.badges.includes(c.id)){this.data.badges.push(c.id);unlocks.push(c.name);earned+=100;}const bests=[];if(complete)for(const [key,value] of [['kills',report?.kills??stats.kills],['headshots',report?.headshots??stats.headshots],['accuracy',(report?.shotsFired??stats.shots)>=10?accuracy(report?.hits??stats.hits,report?.shotsFired??stats.shots):0]])if(value>this.data.bests[key]){this.data.bests[key]=value;bests.push(key.toUpperCase()+' / '+value+(key==='accuracy'?'%':''));}this.data.xp+=earned;const result={xp:earned,unlocks,level:levelProgress(this.data.xp),previousLevel:levelForXP(before),bests,challengeProgress:challengeProgress(this.data).filter((c,i)=>c.current>previous[i].current).map(c=>({name:c.name,current:c.current,target:c.target,complete:c.complete}))};this.save();return result;}
 recordPartial({map,stats,weaponUsage}){if(MAP_KEYS.includes(map)){this.addStats(stats,map,weaponUsage);this.save();}}
 selectEmblem(id){if(!this.data.badges.includes(id))return false;this.data.emblem=id;this.save();return true;}
}
export const career=new Career();
export function favorite(p,kind){const source=kind==='weapon'?p.weaponStats:p.mapStats;return Object.keys(source).sort((a,b)=>(source[b].time||source[b].shots||0)-(source[a].time||source[a].shots||0))[0]??null;}
