import assert from 'node:assert/strict';import fs from 'node:fs';
import {Career,sanitizeCareer,levelProgress,accuracy} from '../progression.js';
import {CHALLENGES,challengeProgress} from '../challenges.js';
import {WEAPONS,PRIMARY_KEYS,SECONDARY_KEYS} from '../weapons.js';import {MAPS,mapKey,normalizeBotCount,MAX_BOTS,DEFAULT_BOTS} from '../maps.js';import {normalizeAllies,MAX_ALLIES} from '../ai.js';
import * as crosshair from '../crosshair.js';import * as THREE from '../vendor/three.module.js';
const engineURL=new URL('../vendor/three.module.js',import.meta.url).href,moduleURL=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64'),storage={data:{},getItem(k){return this.data[k]??null;},setItem(k,v){this.data[k]=v;}};
globalThis.localStorage=storage;
const skins=await import(moduleURL(fs.readFileSync(new URL('../skins.js',import.meta.url),'utf8').replace("from 'three'",`from '${engineURL}'`)));
const p=new Career(storage),stats={kills:8,deaths:1,headshots:7,shots:20,hits:12,plants:2,defuses:2,time:120};
for(const [i,map] of Object.keys(MAPS).entries())p.recordRound({id:'completed-'+i,map,difficulty:'hard',win:true,stats,weaponUsage:{[['rifle','mp5','h45','rifle'][i]]:{kills:8,shots:20,hits:12,time:120}},complete:true,alive:true,damage:0,report:{kills:8,headshots:7,shotsFired:20,hits:12}});
assert.equal(p.data.stats.matches,4);assert.equal(p.data.stats.wins,4);assert.equal(p.data.stats.kills,32);assert.equal(p.data.stats.time,480);assert.equal(p.data.difficultyWins.hard,4);assert.equal(p.data.badges.length,CHALLENGES.length);assert.ok(challengeProgress(p.data).every(c=>c.complete));
const before=JSON.stringify(p.data),xp=p.data.xp;p.recordRound({id:'completed-3'});assert.equal(JSON.stringify(p.data),before,'duplicate result awards nothing');assert.equal(new Career(storage).data.xp,xp,'XP survives reload');assert.equal(new Career(storage).data.stats.shots,80);assert.equal(accuracy(48,80),60);assert.equal(levelProgress(300).level,2);
p.recordPartial({map:'zero',stats:{kills:1,time:15},weaponUsage:{}});assert.equal(p.data.stats.matches,4,'abandoned match does not become a win');assert.equal(p.data.stats.time,495);assert.equal(p.data.xp,xp,'abandoned match cannot farm XP');assert.ok(p.selectEmblem('blacksite'));
for(const broken of [{getItem(){throw Error('Blocked');},setItem(){throw Error('Blocked');}},{getItem(){return '{broken';},setItem(){throw Error('Quota');}},null]){const c=new Career(broken);assert.doesNotThrow(()=>c.recordRound({id:'offline',map:'helix',difficulty:'easy',win:false,stats,weaponUsage:{}}));assert.ok(c.sessionOnly);assert.ok(c.data.xp>0);}
const malformed=sanitizeCareer({xp:Infinity,stats:{kills:-10,hits:999,shots:3},mapStats:{constructor:{wins:99}},badges:['unknown'],weaponStats:{bad:{kills:1}}});assert.equal(malformed.xp,0);assert.equal(malformed.stats.kills,0);assert.equal(malformed.stats.hits,3);assert.deepEqual(malformed.badges,[]);assert.deepEqual(malformed.weaponStats,{});
const balance=JSON.stringify(WEAPONS),profile={...p.data,xp:100000};
for(const weapon of Object.keys(WEAPONS))for(const skin of skins.SKINS){assert.ok(skins.chooseSkin(weapon,skin.id,profile));const root=new THREE.Mesh(new THREE.BoxGeometry(.1,.2,.5),new THREE.MeshStandardMaterial());skins.applySkin(root,skin.id);if(skin.id!=='default'){const shader={uniforms:{},vertexShader:THREE.ShaderLib.standard.vertexShader,fragmentShader:THREE.ShaderLib.standard.fragmentShader};root.material.onBeforeCompile(shader);assert.ok(shader.vertexShader.includes('bsPosition=position'));assert.ok(shader.fragmentShader.includes('diffuseColor.rgb=mix'));assert.ok(Number.isFinite(shader.uniforms.bsPattern.value));}root.geometry.dispose();}
assert.equal(JSON.stringify(WEAPONS),balance,'skins never alter weapon statistics');assert.equal(skins.chooseSkin('rifle','elite',{xp:0,badges:[]}),false);assert.equal(skins.chooseSkin('rifle','bad',profile),false);
assert.equal(crosshair.crosshairGap({...crosshair.CROSSHAIR_DEFAULTS,crossDynamic:false},5,true,10),4);assert.equal(crosshair.normalizeCrosshair({crossGap:Infinity,crossThickness:99,crossShape:'bad'}).crossThickness,4);
// Execute actual UI modules with a small document fixture, including failed storage.
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),elements=new Map(),all=[];
class Element{constructor(tag,attrs){this.tagName=tag.toUpperCase();this.dataset={};this.style={setProperty(k,v){this[k]=v;}};this.listeners={};this.classList={toggle(){},add(){},remove(){}};this.hidden=/\bhidden\b/.test(attrs);this.type=(attrs.match(/type="([^"]+)"/)||[])[1];this.value=(attrs.match(/value="([^"]*)"/)||[])[1]||'';this.id=(attrs.match(/id="([^"]+)"/)||[])[1]||'';this.className=(attrs.match(/class="([^"]+)"/)||[])[1]||'';for(const m of attrs.matchAll(/data-([\w-]+)="([^"]*)"/g))this.dataset[m[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=m[2];}addEventListener(k,f){this.listeners[k]=f;}setAttribute(k,v){this[k]=v;}removeAttribute(k){delete this[k];}}
for(const m of html.matchAll(/<([a-z][\w-]*)\b([^>]*?)>/gi)){const el=new Element(m[1],m[2]);all.push(el);if(el.id){assert.ok(!elements.has(el.id),'unique HTML ID '+el.id);elements.set(el.id,el);}}
const select=selector=>selector.startsWith('.')?all.filter(e=>e.className.split(' ').includes(selector.slice(1))):selector.startsWith('[data-')?all.filter(e=>Object.hasOwn(e.dataset,selector.slice(6,-1).replace(/-([a-z])/g,(_,c)=>c.toUpperCase()))):[];
globalThis.document={getElementById:id=>{assert.ok(elements.has(id),'real UI element '+id);return elements.get(id);},querySelectorAll:select,querySelector:s=>select(s)[0],documentElement:new Element('html',''),body:new Element('body','')};globalThis.window={addEventListener(){},dispatchEvent(){}};
const deps={WEAPONS,MAPS,career:p,levelProgress,accuracy,favorite:(profile,kind)=>Object.keys(kind==='weapon'?profile.weaponStats:profile.mapStats)[0],challengeProgress,CHALLENGES,...skins};
const careerSource=fs.readFileSync(new URL('../career-ui.js',import.meta.url),'utf8').replace(/^import .*$/mg,'').replace(/^export /mg,'');const renderers=new Function(...Object.keys(deps),careerSource+'\nreturn {refreshCareer,refreshSkins,renderReport};')(...Object.values(deps));
const uiDeps={WEAPONS,PRIMARY_KEYS,SECONDARY_KEYS,weaponAudio:{preload(){},setVolume(){},stopAll(){}},MAPS,mapKey,normalizeBotCount,MAX_BOTS,DEFAULT_BOTS,normalizeAllies,MAX_ALLIES,career:p,...skins,...renderers,...crosshair};
const uiSource=fs.readFileSync(new URL('../ui.js',import.meta.url),'utf8').replace(/^import .*$/mg,'').replace(/^export /mg,'');const ui=new Function(...Object.keys(uiDeps),uiSource+'\nreturn {settings,showView,showReport};')(...Object.values(uiDeps));
ui.showView('career');assert.equal(elements.get('view-career').hidden,false);assert.equal(elements.get('view-deploy').hidden,true);assert.ok(elements.get('careerStats').innerHTML.includes('33'));ui.showView('challenges');assert.equal(elements.get('view-challenges').hidden,false);assert.ok(elements.get('challengeList').innerHTML.includes('HEADHUNTER'));const squad=select('[data-squad]').find(e=>e.dataset.squad==='7,8');squad.onclick();assert.equal(ui.settings.allyCount,7);assert.equal(ui.settings.botCount,8);ui.showReport({map:'zero',side:'defend',difficulty:'hard',round:7,wins:4,losses:3,kills:9,deaths:2,headshots:5,shotsFired:20,hits:12,plants:2,defuses:1,sessionXP:555,roundResults:[{round:1,side:'attack',win:true,reason:'Complete'}]},true,'Won');assert.ok(elements.get('resultContext').textContent.includes('BLACKSITE ZERO'));assert.ok(elements.get('resultStats').innerHTML.includes('555'));assert.ok(elements.get('resultHistory').innerHTML.includes('ATTACK'));
console.log('PASS: career persistence, duplicate prevention, partial matches, all ten challenges, unlocks, malformed/blocked/quota storage, all weapon skins without balance changes, crosshair settings, actual Career/Challenges/Armory/report DOM and team presets.');
